name: 'Changelog Enforcer'
description: 'Enforces a repository changelog to be kept up to date.'
inputs:
  changeLogPath:  # id of input
    description: 'Path to the changelog file relative to the repository. Comparison is done using `git diff ... | grep ${changeLogPath}`'
    required: true
    default: 'CHANGELOG.md'
  skipLabel:
    description: 'Name of the label used to skip enforcing a changelog change'
    required: true
    default: 'Skip-Changelog'
runs:
  using: 'node12'
  main: 'dist/index.js'
